source/xinyou1003/config/routes.rb
AhaTest::Application.routes.draw do
  root :to => 'issues#index'
  
  resources :issues

  

end

source/xinyou1003/app/models/issue.rb
class Issue < ActiveRecord::Base
end

source/xinyou1003/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

source/xinyou1003/app/controllers/issues_controller.rb
require 'rest_client'
require 'json'
require 'htmlentities'

class IssuesController < ApplicationController
  before_action :set_issue, only: [:show, :edit, :update, :destroy]
  def get_issues_rest
    # Fetch 100 repositories sorted by starrs
    endpoint = 'https://api.github.com/repos/sinatra/sinatra/issues'
    url = "#{endpoint}"
    
    
    repos = []
    # Fetch the top 1000 repositories (10 pages)
    (1..1).each do |page|
      # Fetch the data and parse the JSON response
      puts "Fetching repos from page #{page}"; STDOUT.flush;
      repos_raw = RestClient.get url, :accept => "application/vnd.github.preview"
      # puts repos_raw
      @issues = JSON(repos_raw)
      
      # issues.each do |i|
      #  puts i['title']
      #  puts i['body']
      #  puts i['url']
      #  puts i['state']
      # end
      # repos.concat(JSON(repos_raw)["items"])
      # Sleep 15 seconds to avoid hitting the API limits for unauthenticated calls
      # sleep(15)
    end
  end


  # GET /issues
  # GET /issues.json
  def index
    # @issues = Issue.all
    get_issues_rest
    @coder = HTMLEntities.new
    # render :nothing => true
  end

  # GET /issues/1
  # GET /issues/1.json
  def show
  end

  # GET /issues/new
  def new
    @issue = Issue.new
  end

  # GET /issues/1/edit
  def edit
  end

  # POST /issues
  # POST /issues.json
  def create
    @issue = Issue.new(issue_params)

    respond_to do |format|
      if @issue.save
        format.html { redirect_to @issue, notice: 'Issue was successfully created.' }
        format.json { render action: 'show', status: :created, location: @issue }
      else
        format.html { render action: 'new' }
        format.json { render json: @issue.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /issues/1
  # PATCH/PUT /issues/1.json
  def update
    respond_to do |format|
      if @issue.update(issue_params)
        format.html { redirect_to @issue, notice: 'Issue was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @issue.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /issues/1
  # DELETE /issues/1.json
  def destroy
    @issue.destroy
    respond_to do |format|
      format.html { redirect_to issues_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_issue
      @issue = Issue.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def issue_params
      params[:issue]
    end
end

source/xinyou1003/app/helpers/application_helper.rb
module ApplicationHelper
end

source/xinyou1003/app/helpers/issues_helper.rb
module IssuesHelper
end

source/xinyou1003/app/views/issues/_form.html.erb
<%= form_for(@issue) do |f| %>
  <% if @issue.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@issue.errors.count, "error") %> prohibited this issue from being saved:</h2>

      <ul>
      <% @issue.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

source/xinyou1003/app/views/issues/edit.html.erb
<h1>Editing issue</h1>

<%= render 'form' %>

<%= link_to 'Show', @issue %> |
<%= link_to 'Back', issues_path %>

source/xinyou1003/app/views/issues/index.html.erb
<h1>Listing issues</h1>

<table>
  <thead>
    <tr>
      <th>Number</th>
      <th>Title</th>
	  <th>Body</th>
      <th>Url</th>
      <th>State</th>
    	
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @issues.each do |issue| %>
      <tr>
      	<td><%= issue['number'] %></td>
      	<td></td>
      	<td><%= issue['url'] %></td>
      	<td><%= issue['state'] %></td>
        <td><%= link_to 'Show', issue %></td>
        <td><%= link_to 'Edit', edit_issue_path(issue) %></td>
        <td><%= link_to 'Destroy', issue, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Issue', new_issue_path %>

source/xinyou1003/app/views/issues/new.html.erb
<h1>New issue</h1>

<%= render 'form' %>

<%= link_to 'Back', issues_path %>

source/xinyou1003/app/views/issues/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_issue_path(@issue) %> |
<%= link_to 'Back', issues_path %>

source/xinyou1003/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AhaTest</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>